package com.hyl.shardingspheretest.dao.model;

import java.io.Serializable;
import java.util.Date;

import lombok.Data;

@Data
public class ShardingFirstDo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.idf
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private Integer idf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.title
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.author
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.date
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.title_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private Integer titleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sharding_first.column_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private Integer columnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.idf
     *
     * @return the value of sharding_first.idf
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public Integer getIdf() {
        return idf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.idf
     *
     * @param idf the value for sharding_first.idf
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setIdf(Integer idf) {
        this.idf = idf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.title
     *
     * @return the value of sharding_first.title
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.title
     *
     * @param title the value for sharding_first.title
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.author
     *
     * @return the value of sharding_first.author
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.author
     *
     * @param author the value for sharding_first.author
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.date
     *
     * @return the value of sharding_first.date
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.date
     *
     * @param date the value for sharding_first.date
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.title_id
     *
     * @return the value of sharding_first.title_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public Integer getTitleId() {
        return titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.title_id
     *
     * @param titleId the value for sharding_first.title_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setTitleId(Integer titleId) {
        this.titleId = titleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sharding_first.column_id
     *
     * @return the value of sharding_first.column_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public Integer getColumnId() {
        return columnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sharding_first.column_id
     *
     * @param columnId the value for sharding_first.column_id
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    public void setColumnId(Integer columnId) {
        this.columnId = columnId;
    }
}