package com.hyl.shardingspheretest.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hyl.shardingspheretest.dao.example.ShardingFirstDoExample;
import com.hyl.shardingspheretest.dao.model.ShardingFirstDo;

public interface ShardingFirstDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    long countByExample(ShardingFirstDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int deleteByExample(ShardingFirstDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int deleteByPrimaryKey(Integer idf);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int insert(ShardingFirstDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int insertSelective(ShardingFirstDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    List<ShardingFirstDo> selectByExample(ShardingFirstDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    ShardingFirstDo selectByPrimaryKey(Integer idf);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int updateByExampleSelective(@Param("record") ShardingFirstDo record, @Param("example") ShardingFirstDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int updateByExample(@Param("record") ShardingFirstDo record, @Param("example") ShardingFirstDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int updateByPrimaryKeySelective(ShardingFirstDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sharding_first
     *
     * @mbg.generated Wed May 19 20:01:27 CST 2021
     */
    int updateByPrimaryKey(ShardingFirstDo record);
}